### ISSUE TITLE
User aware routing

### ISSUE THREAD

**Issue by GaruGaru** [The-Data-Appeal-Company/trino-loadbalancer#4]
We may support user aware routing, this is a possible implementation: 

```yaml
routing:
  rule: round-robin
  users:

    default:
      no_match: FORBID | DEFAULT
      cluster:
        tags:
          workload: etl

    rules:
      - user: 'team-data-science-(.+)'
        cluster:
          name: 'cluster-00'
          tags:
            workload: interactive

      - user: 'etl-(.+)-(dev|beta|prod)'
        cluster:
          name: 'cluster-01'
          tags:
            workload: etl

```
